### ISSUE TITLE
1.1.1+ Upgrade causes go to definition to go to tests

### ISSUE THREAD

**Issue by philipbjorge** [lifeart/ember-language-server#105] opened 2020-05-19 23:01 UTC
Hi --
First of all -- I *love* this extension!

Recently, I updated from 1.1.0 and Go to Definition on a component in a handlebars file started jumping to the component's test file instead of it's component template.

I've given this a shot in versions 1.1.1, 1.2.1, 1.2.2 and 1.3.2 and the issue is the same in all of them.

Things are working on 1.1.0 for me.

How can I help assist debugging this?
I'm guessing something funky is going on in here?
https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/src/definition-providers/template.ts

**Comment by lifeart** [comment] 2020-05-20 05:26
Hi @philipbjorge! Thank you for feedback! Basically, we need to create one more function in “layout-helpers”, called “isTest”. And filter files from registry before output.

Likely here: https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/src/builtin-addons/core/template-definition-provider.ts#L199

But, I need template example and file structure (for test) to be sure. Thank you!

regression caused by https://github.com/lifeart/ember-language-server/commit/983e9dda29bea64728a211621a95ccc6de59ab9f

way to fix it - use logic from updated path matcher - https://github.com/lifeart/ember-language-server/pull/106

**Comment by philipbjorge** [comment] 2020-05-22 00:12
@lifeart -- Really appreciate the rapid fix.
Things have gotten a bit hectic for me over here and I won't be able to test or provide a file structure for at least a few days.

**Comment by lifeart** [comment] 2020-05-30 13:13
Hi @philipbjorge. Possible fixes landed in `UELS@1.5.1`. 

If issue exists - could you please write into this issue and attach minimal reproduction (file structure). Thank you!

**Closed as completed by lifeart** 2020-05-30 13:13 UTC
